[package]
name = "decent_client_launcher"
version = "0.0.3"
description = "Minecraft Launcher - Decent Client"
authors = ["liqwtf"]
license = "MIT"
repository = "https://github.com/Decent-Client/launcher"
edition = "2021"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "decent_client"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0", features = ["macos-private-api", "tray-icon"] }
reqwest = { version = "0.12.8", features = ["json"] }
tokio = { version = "1", features = ["full"] }
minecraft-essentials = {version = "0.2.11", features = [] }
tauri-plugin-system-info = "2.0.5"
tauri-plugin-single-instance = "2.0.0"
tauri-plugin-window-state = "2.0.0"
tauri-plugin-fs = "2.0.0"
tauri-plugin-os = "2.0.0"
windows-version = "0.1.0"
oauth2 = "4.4.2"
image = "0.25"
base64 = "0.22"

[target.'cfg(target_os = "macos")'.dependencies]
tauri-plugin-decorum = "1.1.1"
cocoa = "0.26.0"

[target.'cfg(target_os = "windows")'.dependencies]
enigo = "0.1.3"

